### ISSUE TITLE
A few translation errors

### ISSUE THREAD

**Issue by xmorose** [VolmitSoftware/Adapt#191]
### Problem

Again a few missing spaces, double spaces etc. inside of a few translations as seen in the screenshots:
Two spaces:
![doublespace](https://user-images.githubusercontent.com/53750990/190893849-46fec830-6e95-4fae-a18f-70a7286db9a7.png)
Not sure about this one between the "+" after armor strength and the number, not really important but might be a mistake idk
![Screenshot_10](https://user-images.githubusercontent.com/53750990/190893854-7b504d6b-d851-47ed-816b-a395a51aab29.png)
Villager attraction from the discovery skill:
![Screenshot_9](https://user-images.githubusercontent.com/53750990/190893895-ac42b892-cda6-4366-98c9-0b8c9f427dcb.png)
Experimental resistance from the discovery skill having two percent characters (%) 
![Screenshot_8](https://user-images.githubusercontent.com/53750990/190893917-97fcb13e-e95a-45b3-b513-8b2c0f9a676c.png)

### Minecraft Version

1.19.2

### Adapt Version

1.3.1-1.19.2

### Log

https://mclo.gs/vDjmSyp

**Comment by NextdoorPsycho** [comment]
Fixed

**Comment by xmorose** [comment]
I dont think the issue in Experimental resistance got fixed, i still see double %%
